#!/usr/bin/python3
"""Module that factorizes numbers into a product of two smaller numbers."""
from sys import argv


def print_decomposition(value):
    """Print a simple decomposition of an integer greater than 1."""
    divisor = 2

    if value < 2:
        return

    print()
    print(value, "<- Original value")
    
    while value % divisor:
        divisor += 1

    print("{:.0f} = {:.0f} * {:.0f}".format(value, value / divisor, divisor))
    print(value, "<- Updated value")
    print()


if len(argv) != 2:
    print("Usage: {} <file>".format(argv[0]))
    exit()

try:
    with open(argv[1]) as file:
        line = file.readline()

        while line != "":
            value = int(line.strip())
            print_decomposition(value)
            line = file.readline()

except:
    pass
